[package]
name = "youtube_rust"
version = "0.1.0"
authors = ["Robert Hanson <robert.hanson@solutiondesign.com>"]

[dependencies]
hyper = "~0.11"
tokio-core = "~0.1"
futures = "0.1"
hyper-tls="0.1"
reqwest="0.8"