[package]
name = "youtube_rust"
version = "0.1.0"
authors = ["Robert Hanson <robert.hanson@solutiondesign.com>"]

[dependencies]
reqwest="0.8"
regex = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_urlencoded = "0.5.1"
